# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7cd1c1032ceab0f3aaefd8b2e33d723c"
name = "generative-engine-optimization"
handle = "generative-engine-optimization"
application_url = "https://determine-expenditures-proper-alice.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://determine-expenditures-proper-alice.trycloudflare.com/auth/callback",
  "https://determine-expenditures-proper-alice.trycloudflare.com/auth/shopify/callback",
  "https://determine-expenditures-proper-alice.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
